In [30]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [12]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapse_time = end_time - start_time
print(f"{elapse_time:.4f}")

0.0010


In [13]:
# CPU vs GPU performance
# GPU is faster especially for matrix multiplication. Why?
# CPU: few powerful cores
# GPU: thousands of smaller parallel cores
# -> use GPU for training efficiency

# GPU tensors
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

# CPU numpy arrays
np_rand1 = np.random.rand(10000, 10000)
np_rand2 = np.random.rand(10000, 10000)

# GPU timing
torch.cuda.synchronize()   # to proper time GPU
start_time = time.time()
rand = torch.matmul(torch_rand1, torch_rand2)  # matrix multiplication 
torch.cuda.synchronize()
end_time = time.time()
elapsed_time = end_time - start_time
print(f"GPU time: {elapsed_time:.8f} seconds")

# CPU timing
start_time = time.time()
rand = np.dot(np_rand1, np_rand2) # dot product (similar to matrix multiplication)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU time: {elapsed_time:.8f} seconds")

GPU time: 2.11872029 seconds
CPU time: 17.43576574 seconds


In [14]:
# General knowledge

In [15]:
# embeddings,
# torch.multinomial

# torch.cat
# torch.stack,

# torch.tril, torch.triu,

# input.T / input.transpose, 
# nn.Linear, 
# F.softmax (show all the examples of functions/methods with pytorch docs)

In [16]:
# torch.multinomial: randomly samples indices from a probability distribution:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor

# Draw 10 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [17]:
# torch.cat: Concatenation
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)  # Join tensors together along dimension 0
out

tensor = torch.tensor([[1, 2],
                       [3, 4]])
out = torch.cat((tensor, torch.tensor([[5], [6]])), dim=1)  # Join tensors together along dimension 1
out

# Very common for:
# combining embeddings
# building sequences
# appending generated tokens
# batching data

tensor([[1, 2, 5],
        [3, 4, 6]])

In [18]:
# creates a lower triangular matrix
out = torch.tril(torch.ones(5, 5))
out

# This exact operation is used for:
# causal masking
# autoregressive generation
# because GPT should NOT see future tokens

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
# creates an upper triangular matrix
out = torch.triu(torch.ones(5, 5))
out

# causal masking
# future positions
# invalid attention regions

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [20]:
# masked_fill() replaces elements in a tensor wherever a mask is True
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out
# == 0: converts to boolean mask -> 1 = False, 0 = True. Replace with float('-inf') where it's True

# 1. Attention masking: Hide future tokens
# 2. Padding masks: Ignore padding tokens
# 3. Data cleaning: Replace invalid values

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
# exp(x)= e^x for all entries in out
torch.exp(out)

# This is the core trick behind:
# softmax
# attention masking
# probability conversion

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [22]:
# Swap dimension 0 and 1
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [23]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.8103, -3.0125,  6.1899], grad_fn=<SqueezeBackward4>)


In [25]:
# tensors

randint = torch.randint(-100, 100, (6,))
print("randint")
print(randint)

tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print("tensor")
print(tensor)

zeros = torch.zeros(2, 3)
print("zeros")
print(zeros)

ones = torch.ones(3, 4)
print("ones")
print(ones)

# Uninitialized memory
input = torch.empty(2, 3)
print("empty memory")
print(input)

# array range: 0 -> n-1
arange = torch.arange(5)
print("array range: 0 -> n-1")
print(arange)

# tensor of evenly spaced numbers between 3 and 10, take 5 steps
linspace = torch.linspace(3, 10, steps=5)
print("linspace")
print(linspace)

# evenly spaced on a logarithmic scale
logspace = torch.logspace(start=-10, end=10, steps=5)
print("logspace")
print(logspace)

# 10^(-10)
# 10^(-5)
# 10^(0)
# 10^(5)
# 10^(10)

#5 × 5 identity matrix
eye = torch.eye(5)
print("identity matrix")
print(eye)


a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
print("empty_like")
print(empty_like)


# .view() reshapes a tensor WITHOUT changing the underlying data
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

y = x.view(3, 2)
# tensor([
#  [1, 2],
#  [3, 4],
#  [5, 6]
# ])

print("view")
print(y)

# torch.multinomial() samples random indices from a probability distribution
# probs = torch.tensor([0.7, 0.2, 0.1])
# index 0 -> 70% chance
# index 1 -> 20% chance
# index 2 -> 10% chance

SyntaxError: invalid syntax (440981277.py, line 75)

In [ ]:
# Neural Network
# y=Wx+b (linear)
# W: weight, b: bias
# y: output, x: input vector

import torch.nn as nn
sample = torch.tensor([10., 20., 15.])
linear = nn.Linear(3, 3, bias=False)   #in, out size = 3
print(linear.weight)   #y = Wx -> W is 3x3 matrix
print(linear(sample))

# https://docs.google.com/presentation/d/1xslguVqu0sHANOhJduP31GJLFX-LbjVGS1wfc7Jvy6A/edit?usp=sharing

# Input -> Hidden layers -> Output
# The node at each hidden layers are activation functions
# Activation functions:
# - Linear
# - Sigmoid
# - ReLU
# - Tanh

# The lines connecting layers are weights -> put it in matrix (eg y1=w11​x1+w12​x2+w13​x3)
# Training a neural network means: adjusting these weights so outputs become more correct
# Gradient descent updates them during learning

# Mean Squared Error (MSE) is a popular loss function for regression algorithms, 
# measuring the average squared difference between predicted and actual values
# Lower MSE indicates better model performance

# MLP Multilayer perceptrons (General purpose predictions)
# Transformers (LLM)
# RNN (recurrent neural networks) processing sequential data
# CNN: computer vision

In [ ]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_out = F.softmax(tensor1, dim=0)
print(softmax_out)

# Softmax: convert a vector of raw scores (logits) into a probability distribution, 
# where each value ranges between 0 and 1 and all values sum to 1
# https://en.wikipedia.org/wiki/Softmax_function to see the func

# Exponentials amplify differences -> amplifies larger values and reduces smaller values -> confident prediction

In [ ]:
# Embedding Vectors

# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])  
# embeddings for: token 1, 5, 3, 2

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 6), where 4 is the number of inputs and 6 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)


# Embedding
# representation learning that maps complex, high-dimensional data into a lower-dimensional vector
# Similar things get similar vectors
# Different things get distant vectors

# In LLM
# Text
# → Token IDs
# → Embeddings
# → Transformer layers
# → Predictions

In [ ]:
# Dot product
# a · b = a1b1 + a2b2 + a3b3

# a = [1, 2, 3]
# b = [4, 5, 6]

# dot = 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32

# Matrix multiplication
# (row from first matrix) DOT (column from second matrix)

a = torch.tensor([[1,2],[3,4],[5,6]])   # 3x2
b = torch.tensor([[7,8,9],[10,11,12]])  # 2x3
# print(a @ b)   # 3x3 same as matmul
print(torch.matmul(a, b))

In [ ]:
# int vs float

int_64 = torch.randint(3, (3, 2)).float()  #[0, 3) size (3,2)
#type int64
float_32 = torch.rand(2,3)  # float betwwen (0,1)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

In [36]:
# Activation functions: ReLU, Sigmoid, tanh
x = torch.tensor([10], dtype=torch.float32)
y = F.relu(x)
print("tanh", y)
y = F.sigmoid(x)
print("tanh", y)
y = F.tanh(x)
print("tanh", y)

tanh tensor([10.])
tanh tensor([1.0000])
tanh tensor([1.])
